# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Joshua Concon
tagline:          'Computer Science Student'
description:      'Computer Science Student at the University of Toronto Scarborough'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Joshua Concon'
  url:            https://twitter.com/mdo

future:           true
paginate:         5

# Custom vars
linkedin:         https://ca.linkedin.com/in/joshuaconcon

github:           https://github.com/JoshuaConcon

gems: [jekyll-paginate]
